### ISSUE TITLE
Last Saved by Editor section is duplicated at the bottom of KB articles

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#16119]
## Describe the defect
On the KB article content type, the Last Saved by Editor section is duplicated at the bottom of the content as well as being in the left column, where it should be.

**D10**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/268625e1-ecbb-4198-b8b5-9f7956dbe84c)

**Prod**
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/f4794d4a-e844-4c97-a1ba-e21fa864b0a2)

## To Reproduce
1. Go to a KB article on the D10 environment, [example](https://vacms-12252-drupal-10-opslrfeufzwsvhxx2uuv1wmvjbiq7wuq.ci.cms.va.gov/help/va-medical-centers-vamcs/about-stories-content-for-vamcs/how-to-add-a-story)
2. Scroll down to the bottom
3. Notice that the "Last Saved by Editor" section is in the left column and also directly above the "Was it helpful" heading

## AC / Expected behavior

- [ ] Last saved by Editor section should only be on the left column, under the left nav

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by edmund-dunn** [comment]
This seems to be something lingering in the database. It can't be replicated locally and is not on prod. It is a simple fix and will ned to be verified post deployment.

**Comment by edmund-dunn** [comment]
It is fixed within layout builder for now.

**Comment by laflannery** [comment]
I still see this in the D10 tugboat, is that ok?
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/db48b4ba-b4a8-4d91-b4d0-3f0e3add004a)

**Comment by edmund-dunn** [comment]
This has been fixed and merged into the D10 branch.
