### ISSUE TITLE
Avoid deadlock issues on {node_field_data} and {user_field_data} table

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2012]
## Description

When saving a large amount (~50) nodes at the same time table deadlocks occur:

See https://www.drupal.org/project/drupal/issues/2846880

## Acceptance Criteria

- [ ] 50 or more nodes may be saved simultaneously without triggering deadlock errors

**Comment by acrollet** [comment]
We believe that this should be resolved by the addition of memcache, we will run the test script in the linked d.o. issue with and without memcache to confirm, as part of #5083 .

**Comment by ndouglas** [comment]
Still an issue, even with memcache, unless I'm missing something:

<img width="706" alt="Screen Shot 2021-04-27 at 5 46 20 PM" src="https://user-images.githubusercontent.com/1318579/116316910-9efd8780-a780-11eb-8555-f955bdc677fa.png">

**Comment by acrollet** [comment]
ok, seems like the deadlock issue is at the table level during the insert, rather than a caching issue. @indytechcook do we know of a current use case for saving large numbers of nodes at once (e.g. has this cropped up during bulk publishing?) or is this a proactive scalability issue?

**Comment by acrollet** [comment]
Since memcache did not resolve the issue and there is no RTBC core patch, the previous estimate is invalid. @ndouglas I'm bumping this from this sprint to clear time for tier 2 support + D9 work.
