### ISSUE TITLE
Term references on R&S content should not throw broken link errors

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3210]
## Description

R&S nodes have tags that trigger broken links report.
This may be happening because we have not set URL aliases for terms yet, or because of other permission-related weirdness that prevents node links report from accessing term pages.

<img width="1266" alt="Screen Shot 2020-10-19 at 3 53 25 PM" src="https://user-images.githubusercontent.com/16477724/96516224-fba54600-1223-11eb-8b0b-5b88bfe3540e.png">

## Acceptance Criteria

- [x] allow anonymous users to `view` taxonomy terms

**Comment by kaise-lafrai** [comment]
Hi @oksana-c. Can you show me with a screenshot of the specific permission I should change for anonymous user? Thanks

**Comment by kaise-lafrai** [comment]
@oksana-c I can't seem to find that specific permission mentioned in the AC. Do I need to install another contrib module?

**Comment by kaise-lafrai** [comment]
@oksana-c We could also skip /taxonomy/term/* by added that to node link report config.

**Comment by oksana-c** [comment]
@kaise-lafrai , taxonomy term pages are currently rendered as views, so it looks like permissions to view these pages come from the view configuration. 
also, @ethanteague is working on specific views for LC terms, so it seems that this issue should also be handled by Ethan. 
One note, since LC terms will have separate views compared to all other terms in Drupal, we'd want to enable anonymous user access to only LC terms and not for any others.

**Comment by kaise-lafrai** [comment]
@oksana-c Okay thanks. I will remove myself from this issue and let @ethanteague pick it up or I can pick it up after Ethans work is completed and merged.

**Comment by ethanteague** [comment]
Addressed in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3321
@oksana-c

**Comment by swirtSJW** [comment]
Seems like this is an issue even with the ter listing pages accessible, they are still getting flagged as broken.   I create an issue in the module  https://www.drupal.org/project/node_link_report/issues/3180747
